default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password:
  database: rails_api
  port: 3306
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default